id: I77C49534
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-18T11:19:29+00:00'
last_modified: '2022-06-08T04:12:26.430688+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2788
  title: བཀྲ་ཤིས་ལྷུན་པོའི་ཞལ་འདོན་ཆོས་སྤྱོད་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D3B8:
      image_group_id: I1KG3143
      title: Volume 1 of bkra shis lhun po'i 'phags tshogs 'dus sde rin po che'i zhal
        'don chos spyod rab gsal
      total_pages: 650
      order: 1
      base_file: D3B8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
